"""update pcm_analysis schema

Revision ID: 7aebd063f4a3
Revises: a263ba192205
Create Date: 2025-08-22 22:03:38.858948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aebd063f4a3'
down_revision: Union[str, Sequence[str], None] = 'a263ba192205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pcm_analysis', 'vectors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pcm_analysis', 'scripts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pcm_analysis', 'emotions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pcm_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_pcm_analysis_agent_id'), table_name='pcm_analysis')
    op.drop_constraint(op.f('pcm_analysis_agent_id_fkey'), 'pcm_analysis', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('pcm_analysis_agent_id_fkey'), 'pcm_analysis', 'agents', ['agent_id'], ['id'])
    op.create_index(op.f('ix_pcm_analysis_agent_id'), 'pcm_analysis', ['agent_id'], unique=False)
    op.alter_column('pcm_analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pcm_analysis', 'emotions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pcm_analysis', 'scripts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pcm_analysis', 'vectors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
