"""add pcm_analysis table

Revision ID: a263ba192205
Revises: d85b2a870683
Create Date: 2025-08-22 21:59:36.889823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a263ba192205'
down_revision: Union[str, Sequence[str], None] = 'd85b2a870683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcm_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('vectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('guideline', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcm_analysis_agent_id'), 'pcm_analysis', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pcm_analysis_agent_id'), table_name='pcm_analysis')
    op.drop_table('pcm_analysis')
    # ### end Alembic commands ###
